imagine: Visual Studio 2019
init:
  - git config --global core.autocrlf input
clone_folder: c:\projects\TestCI
shallow_clone: true             
matrix:
    fast_finish: false
platform:
    - x64
    - x86
configuration:
    - Debug
    - Release
environment:
    matrix:
        - TOOLCHAIN: msvc15
        - TOOLCHAIN: msvc17
        - TOOLCHAIN: msvc19
install:
build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure