version: 1.0.{build}
image: Visual Studio 2015
clone_folder: c:\projects\TestCI
shallow_clone: true             
matrix:
   fast_finish: false
platform:
    - x64
    - x86
configuration:
    - Debug
    - Release
environment:
    matrix:
        - TOOLCHAIN: msvc15
install:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%
build_script:
  - mkdir ../build
  - cmake ../TestCI
  - make -j
  - cd ./bin/

test_script:
  - ./test_TestCI