version: 1.0.{build}
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
clone_folder: c:\projects\TestCI
shallow_clone: true           
matrix:
   fast_finish: false
platform:
    - x64
    - x86
configuration:
    - Debug
    - Release
environment:
    matrix:
        - TOOLCHAIN: msvc12
    address:
        secure:qBBzLyQWoWOQIc2R0jpb7j93WkoRoHekpmj1QjhRux504L8ywYMJa5iyneHj6cXJAqk1sagcd45Wxw44uh4p9GXp8QoB85mZ0QpS+VRI7Gc=  
before_build:
 - git clone address
 - mkdir test
 - cd test
 - cmake .. %CMAKE_CONFIGURE_FLAGS%
 - cmake --build . %CMAKE_BUILD_FLAGS%
 - cd C:\projects\TestCI
 - mkdir clones
 - git clone https://github.com/unloguc/TestCI.git
build_script:
  - cd C:\projects\TestCI
  - mkdir build
  - cd build
  - cmake .. %CMAKE_CONFIGURE_FLAGS%
  - cmake --build . %CMAKE_BUILD_FLAGS%
#  - cd bin
# - '**\*.test_TestCI.exe'
test_script:
 - cmd: C:\projects\TestCI\build\bin\test_TestCI.exe