version: 1.0.{build}
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
clone_folder: c:\projects\TestCI
shallow_clone: true             
matrix:
   fast_finish: false
platform:
    - x64
    - x86
configuration:
    - Debug
    - Release
environment:
    matrix:
        - TOOLCHAIN: msvc12
build_script:
  - mkdir build
  - cd build
  - cmake .. %CMAKE_CONFIGURE_FLAGS%
  - cmake --build . %CMAKE_BUILD_FLAGS%
  - cd bin
# - '**\*.test_TestCI.exe'
test_script:
  - cmd: C:\projects\TestCI\build\bin\test_TestCI.exe