version: 1.0.{build}
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
clone_folder: c:\projects\TestCI
shallow_clone: true             
matrix:
   fast_finish: false
platform:
    - x64
    - x86
configuration:
    - Debug
    - Release
environment:
    matrix:
        - TOOLCHAIN: msvc12
before_build:
 -if [ ! -d /var/www/html/.git ] then
 - git clone git clone https://github.com/unloguc/Test_CI-private- /var/www/html
 - fi
 - mkdir test
 - cd test
 - cmake .. %CMAKE_CONFIGURE_FLAGS%
 - cmake --build . %CMAKE_BUILD_FLAGS%
 - cd C:\projects\TestCI
 - mkdir clones
 -if [ ! -d /var/www/html/.git ] then
 -  git clone https://github.com/unloguc/TestCI /var/www/html
 - fi
build_script:
  - cd C:\projects\TestCI
  - mkdir build
  - cd build
  - cmake .. %CMAKE_CONFIGURE_FLAGS%
  - cmake --build . %CMAKE_BUILD_FLAGS%
#  - cd bin
# - '**\*.test_TestCI.exe'
test_script:
 - cmd: C:\projects\TestCI\build\bin\test_TestCI.exe